services:
  flask:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: flask_app
    volumes:
      - ./app/data:/app/data

  nginx:
    image: nginx:latest
    container_name: nginx_app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl/nginx.crt:/etc/nginx/ssl/nginx.crt
      - ./nginx/ssl/nginx.key:/etc/nginx/ssl/nginx.key
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - flask
